
server:
    port: 4200
spring:
    datasource: 
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: password
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xjlkLCL3E
            client:
                registration:
                    cognito:
                        client-id: 2amqsstk11k074rfemhjno95cd
                        client-secret: eg51popto978kop48aa1qtel2ij4h2vvo9j9hqjt7jck0op0utb
                        scope: openid
                        redirect-uri: http://localhost:4200/login/oauth2/code/cognito
                        clientName: springauth
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xjlkLCL3E
                    

                      