CREATE TABLE IF NOT EXISTS applications (
   id SERIAL,
   first_name VARCHAR(20) NOT NULL,
   middle_name VARCHAR(20),
   last_name VARCHAR(20) NOT NULL,
   gender VARCHAR(20) NOT NULL,
   birth_date DATE NOT NULL,
   birth_country VARCHAR(20) NOT NULL,
   citizen_country VARCHAR(20) NOT NULL,
   email VARCHAR(50),
   phone VARCHAR(10) NOT NULL,
   current_address VARCHAR(255) NOT NULL,
   race VARCHAR(20) NOT NULL,
   eye_color VARCHAR(20) NOT NULL,
   hair_color VARCHAR(20) NOT NULL,
   height int NOT NULL,
   degree VARCHAR(20) NOT NULL,
   degree_name VARCHAR(20) NOT NULL,
   adv_overthrow BOOLEAN NOT NULL,
   reli_persecuted BOOLEAN NOT NULL,
   nazi BOOLEAN NOT NULL,
   crimes BOOLEAN NOT NULL,
   PRIMARY KEY(id)
);